### ISSUE TITLE
Forum 2 semestre ADS

### ISSUE THREAD

**Issue by Araujo2019** [gleyconxavier/forum02-web-ads#1]
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Inconsolata|Lexend+Zetta|Roboto+Condensed&display=swap" rel="stylesheet">

        <style>

            @font-face{
                font-family: "FreePixel";
                src: url('assets/fonts/FreePixel.ttf');
            }

            *{
                padding: 0;
                margin: 0;
            }

            body {
                font-family: 'Inconsolata', monospace;
                
background-color: antiquewhite;
            }

            a {
                font-family: 'FreePixel';
                text-decoration: none;
                font-size: 2vw;
                color: rgb(128,128,128);
            }

            body h1, h3, p {
                padding-left: 20px;
            }

            /* media insite divs */

            img {
                max-width: 100%;
                height: auto;
                border-radius: 12px;
                border: 1px dashed #cecece;
            }

            video {
                max-width: 100%;
                height: auto;
            }

            header {
                margin: 10px;
                padding-left: 20px;
            }

            footer{
                font-family: 'FreePixel', sans-serif;
                position: fixed;
                left: 0;
                bottom: 0;
                width: 100%;
                background-color: grey;
                color: antiquewhite;
                text-align: center;
            }

            /* gleycon */

            .secret {
                display: none;
            }

            .area {
                border-radius: 30px;
                background-color: #fff;
                padding: 25px;
                width: 50vw;
                margin: auto;
                float: left;
                margin-left: 2vw;
                margin-bottom: 15px;
                box-shadow: 0 10px 6px -6px #00008B;
            }

            #cursos {
                text-align: left;
            }

            #warning {
                color: red;
                border: 4px solid red;
                border-radius: 13px;
                background-color: black;
                font-size: 3em;
                display: none;
            }

            #avatar{
                width: 35%;
                overflow: hidden;
                border: 3px solid black;
            }

            /* xavier */

            #cursos {
                border: 1px solid black;
                overflow-x:auto;

            }

            #aniHid {
                display: none;
            }

            #avatar:hover #aniHid{
                display: inline-block;
                border: 4px solid black;
                width: 90%;
            }

            

            #avatar:hover {
                animation: loucura 1s linear infinite;
            }

            /* xavier gleycon */

            @keyframes loucura {
                0% {
                     border-color: red;
                }

                25%      border-color: blue;
                }

                100% {
                    border-color: red;
                }
            }

            /* gleyconxavier */

    @media (min-width: 768px) and (max-width: 1024px) {

        #warning {
            display: inline-block;
            font-size: 25px;
        }
    
    }

    @media (min-width: 768px) and (max-width: 1024px) and (orientation: landscape) {
    
        #warning {
            display: inline-block;
        }
    
    }

    @media (min-width: 481px) and (max-width: 767px) {
    
        #warning {
            display: inline-block;
            font-size: 22px;
        }
    
    }

    @media (min-width: 320px) and (max-width: 480px) {
    
        #warning {
            display: inline-block;
            font-size: 18px;
        }
    
    }

        </style>

        <script>
        </script>

        <title>Forum 2 semestre | Projeto</title>
    </head>

    <body>

        <header>
            <h1>Bem vindo!</h1>
            <h3>Minhas informações</h4>

            <div id="warning">
                <p>Atenção! Você está visualizando em resolução baixa!</p>
                <p>O mapa de imagem talvez não funcionará (entre outros), atente para resoluções maiores que 1280x1024</p>
            </div>
        </header>

        <div class="area" id="avatar">
                        <img  usemap="#map"   <img <img src="https://imageshack.com/i/poQakbDrj"/>       <map name="map">
   <area shape="circle" coords="201,214,63" <a <a <a href="https://www.google.com"> 
</a>      
</body>
</html>
          </map>
        </div>

        <div class="area" id="cursos">

            <table style="width:100%">
                <h3>Formações</h3><br>
                    <t
r>
                      <th>Curso</th>
                                                        </tr>

                    <tr>
                      <td>Curso Completo em Computação avançada</td>
                                         </tr>

                    <tr>
                      <td>Curso Sistema MBR Makro</td>
                      
                                           
                    </tr>

                    <tr>
                        <td>Curso Sistema PJE CNJ</td>
                      
                                                 
                    </tr>
                   
                  </table>
        </div>

        <div class="area secret">

             id="bestKeygen"></audio>
        </div>

        <div class="area">
            <video controls>
                  
<source src="assets/videos/curso.mp4" type="video/mp4">                 Seu navegador não suporta o elemento <code>video</code>.
            </video>
                             </div>

        <footer>Will Araujo | 2019</footer>

        <script>
            var audio = document.getElementById("bestKeygen");
            audio.volume = 0.1;
        </script>

    </body>
</html>

**Comment by gleyconxavier** [comment]
Qual o problema?

**Comment by Araujo2019** [comment]
Opa Sou do do curso de sistema de informação Unopar.

Enviado do meu iPhone

Em 7 de set de 2019, à(s) 16:31, Gleycon Xavier <notifications@github.com<mailto:notifications@github.com>> escreveu:


Qual o problema?
